autoclose_curlybraces: true
autoclose_doublequotes: true
autoclose_parentheses: true
autoclose_singlequotes: true
autoclose_squarebrackets: true
font_color: '#ffffff'
font_family: monospace
font_size: 14
horizontal_scrollbar_active_bg: '#8a7575'
horizontal_scrollbar_color: '#383030'
horizontal_scrollbar_trough_color: '#2e2724'
horizontal_scrollbar_width: 8
insertion_blink: false
insertion_color: '#75715E'
menu_active_bg: '#001d6c'
menu_active_fg: '#ffffff'
menu_bg: '#161616'
menu_fg: '#42be65'
menubar_active_bg: '#001d6c'
menubar_active_fg: '#ffffff'
tab_size: 4
text_bottom_lineheight: '1'
text_selection_bg: '#1b444f'
text_top_lineheight: '1'
text_wrap: none
textarea_background_color: '#161616'
textarea_border: 0.5
textarea_padding_x: '5'
textarea_padding_y: '5'
vertical_scrollbar_active_bg: '#8a7575'
vertical_scrollbar_color: '#383030'
vertical_scrollbar_trough_color: '#2e2724'
vertical_scrollbar_width: 8
